[tool]
[tool.poetry]
name = "SilgiUserbot_Deployer"
version = "1.0"
description = "Automatic Deploy âš ğ‘ºğ‘°ğ‘³ğ‘®ğ‘° ğ‘¼ğ‘ºğ‘¬ğ‘¹ğ‘©ğ‘¶ğ‘» âšğŸ’» to Heroku"
authors = ["Silgi <@atondusalamde>"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
